/*
 * JavaWars - browser game that teaches Java
 * Copyright (C) 2008-2009  Bartlomiej N (nbartlomiej@gmail.com)
 * 
 * This file is part of JavaWars. JavaWars is free software: you can 
 * redistribute it and/or modify it under the terms of the GNU General 
 * Public License as published by the Free Software Foundation, either 
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 * 
 */

/*
 * JWField.java
 *
 * Created on February 15, 2008, 5:31 PM
 *
 * Bartek N, nbartlomiej{at}gmail.com
 */

package javawars;

/**
 *
 * @author bartek
 */
public class JWField {
    
    int height;
    int gem;
    int robot;
    
    /** Creates a new instance of JWField */
    public JWField(int newHeight, int newGem, int newRobot) {
        height = newHeight;
        gem = newGem;
        robot = newRobot;
    }

    public int getHeight() {
        return height;
    }

    public int getGem() {
        return gem;
    }

    public int getRobot() {
        return robot;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public void setGem(int gem) {
        this.gem = gem;
    }

    public void setRobot(int robot) {
        this.robot = robot;
    }

    @Override
    public boolean equals(Object object) {
        
       if (object instanceof JWField) {
            JWField compared = (JWField)(object);
            
            if (this.getGem() == compared.getGem() 
                    && this.getHeight() == compared.getHeight() 
                    && this.getRobot() == compared.getRobot() )
                return true;
        }
        return false;

        
    }

    //hashCode() has been generated by ide (netbeans 6). 
    //i do not happen to know why these numbers (7 & 43) were chosen
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 43 * hash + this.height;
        return hash;
    }
    
    public static void main(String args[]){
        
    }

    
}
